[project]
name = "utilities"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.0",
    "loguru>=0.7.3",
    "send2trash>=1.8.3",
]
